config/routes.rb
MongoDB::Application.routes.draw do
  resources :contadors

  resources :questions

  get "answer/new"
  get "question/new"
  get "main/index"

  
  

   root 'main#index'

end

app/models/contador.rb
class Contador
  include Mongoid::Document
  field :contC, type: Integer
  field :contPg, type: Integer
end

app/models/question.rb
class Question
  include Mongoid::Document
  field :pregunta, type: String
  field :respuesta, type: String
  field :pista, type: String
  validates_presence_of :pregunta
  validates_presence_of :respuesta
  validates_presence_of :pista
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contadors_controller.rb
class ContadorsController < ApplicationController
  before_action :set_contador, only: [:show, :edit, :update, :destroy]

  # GET /contadors
  # GET /contadors.json
  def index
    @contadors = Contador.all
  end

  # GET /contadors/1
  # GET /contadors/1.json
  def show
  end

  # GET /contadors/new
  def new
    @contador = Contador.new
  end

  # GET /contadors/1/edit
  def edit
  end

  # POST /contadors
  # POST /contadors.json
  def create
    @contador = Contador.new(contador_params)

    respond_to do |format|
      if @contador.save
        format.html { redirect_to @contador, notice: 'Contador was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contador }
      else
        format.html { render action: 'new' }
        format.json { render json: @contador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contadors/1
  # PATCH/PUT /contadors/1.json
  def update
    respond_to do |format|
      if @contador.update(contador_params)
        format.html { redirect_to @contador, notice: 'Contador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contadors/1
  # DELETE /contadors/1.json
  def destroy
    @contador.destroy
    respond_to do |format|
      format.html { redirect_to contadors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contador
      @contador = Contador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contador_params
      params.require(:contador).permit(:contC, :contPg)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
 def index
    @questions = Question.all
    @x =  @questions.shuffle[0] 
    @a =  @questions.shuffle[1].respuesta 
    @b =  @questions.shuffle[2].respuesta 
    @c =  @questions.shuffle[3].respuesta    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'La Pregunta Fue Agregada Existosamente.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'La Pregunta Fue Agregada Existosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:pregunta, :respuesta, :pista)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contadors_helper.rb
module ContadorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/contadors/_form.html.erb
<%= form_for(@contador) do |f| %>
  <% if @contador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contador.errors.count, "error") %> prohibited this contador from being saved:</h2>

      <ul>
      <% @contador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contC %><br>
    <%= f.text_field :contC %>
       <%= f.label :contPg %><br>
    <%= f.text_field :contPg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contadors/edit.html.erb
<h1>Editing contador</h1>

<%= render 'form' %>

<%= link_to 'Show', @contador %> |
<%= link_to 'Back', contadors_path %>

app/views/contadors/index.html.erb
<h1>Listing contadors</h1>

<table>
  <thead>
    <tr>
      <th>Cont</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contadors.each do |contador| %>
      <tr>
        <td><%= contador.contC %></td>
        <td><%= contador.contPg %></td>
        <td><%= link_to 'Show', contador %></td>
        <td><%= link_to 'Edit', edit_contador_path(contador) %></td>
        <td><%= link_to 'Destroy', contador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contador', new_contador_path %>

app/views/contadors/new.html.erb
<h1>New contador</h1>

<%= render 'form' %>

<%= link_to 'Back', contadors_path %>

app/views/contadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cont:</strong>
  <%= @contador.contC %>
   <%= @contador.contPg %>
</p>

<%= link_to 'Edit', edit_contador_path(@contador) %> |
<%= link_to 'Back', contadors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MongoDB" %></title>
     <link href='http://fonts.googleapis.com/css?family=Covered+By+Your+Grace' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" <%= link_to "MongoDB", root_path %></a>
          
          <div class="container nav-collapse">
            <ul class="nav">
              <li> <%= link_to 'Agregar Pregunta', questions_path %></li>
              
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
      </div>
   

    </div> <!-- /container -->

  </body>
</html>

app/views/main/index.html.erb
<p id="notice"><%= notice %></p>  
 
 <% @cont = 0 %>
<div class="container">
	<div class="row-fluid">
          <br>
          <br>
           <div class="hero-unit"> 
    <% if @x.nil? %>
             lol
      <% else %>
      <div><%=@x.pregunta %></div>             
      <% if (@x.respuesta != @a) && (@x.respuesta != @b) && (@x.respuesta != @c) && (@a != @b) && (@b != @c)  && (@c != @a ) %>
       <br>
      <% @array = [ @x.respuesta, @a, @b, @c, ].shuffle %>      
          <a href="#myModal2" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[0] %></a>
          <!-- Modal -->
          <div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
            <% if @x.respuesta ==  @array[0] %>
            <div class="modal-header">
                    
              <h3 id="myModalLabel2">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[0] %></p>    
              <p>Bien hecho</p>               
            </div>
            <% @cont = 1 %>           
            <% else %>
            <div class="modal-header">               
              <h3 id="myModalLabel2">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[0] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
             </div>           
            <br >
             <% @cont = 0 %>   
            <% end %>
            <div class="modal-footer">          
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
          <br>   
        
          <a href="#myModal3" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[1] %></a>
          <!-- Modal -->
          <div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3" aria-hidden="true">
            <% if @x.respuesta ==  @array[1] %>
            <div class="modal-header">
                  
              <h3 id="myModalLabel3">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[1] %></p>    
              <p>Bien hecho</p>               
            </div>
                <% @cont = 1 %>       
            <% else %>
            <div class="modal-header">             
              <h3 id="myModalLabel3">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[1] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
        </div>
            <br >   
             <% @cont = 0 %>   
        <% end %>
            <div class="modal-footer">
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
            <br>         
      
        
          <a href="#myModal4" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[3] %></a>
          <!-- Modal -->
          <div id="myModal4" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
            <% if @x.respuesta ==  @array[3] %>
            <div class="modal-header">                   
              <h3 id="myModalLabel3">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[3] %></p>    
              <p>Bien hecho</p>               
            </div>
              <% @cont = 1 %>       
            <% else %>
            <div class="modal-header">                 
              <h3 id="myModalLabel3">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[3] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
        </div>
            <br >   
             <% @cont = 0 %>   
        <% end %>
            <div class="modal-footer">           
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
            <br>         
      
        <a href="#myModal5" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[2] %></a>
          <!-- Modal -->
          <div id="myModal5" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
            <% if @x.respuesta ==  @array[2] %>
            <div class="modal-header">                
              <h3 id="myModalLabel4">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[2] %></p>    
              <p>Bien hecho</p>               
            </div>
          <% @cont = 1 %>       
            <% else %>
            <div class="modal-header">                
              <h3 id="myModalLabel4">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[2] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
        </div>           
            <br >    
             <% @cont = 0 %>   
             <% end %>
            <div class="modal-footer">           
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
            <br>
            
   
     <% else %>
      
             <% @y = true %>           
          <% while @y %>
               <% @a =  @questions.shuffle[0].respuesta %>
               <% @b =  @questions.shuffle[1].respuesta %>
               <% @c =  @questions.shuffle[2].respuesta %>                      
             <% if (@x.respuesta != @a) && (@x.respuesta != @b) && (@x.respuesta != @c) && (@a != @b) && (@b != @c)  && (@c != @a ) %>
                   <% @array = [ @x.respuesta, @a, @b, @c, ].shuffle %>
      
          <a href="#myModal2" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[0] %></a>
          <!-- Modal -->
          <div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
            <% if @x.respuesta ==  @array[0] %>
            <div class="modal-header">
                  
              <h3 id="myModalLabel2">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[0] %></p>    
              <p>Bien hecho</p>               
            </div>
               <% @cont = 1 %>     
            <% else %>
            <div class="modal-header">
                   
              <h3 id="myModalLabel2">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[0] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
        </div>
            <br >
             <% @cont = 0 %>   
        <% end %>
            <div class="modal-footer">
            
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
            <br>   
           
          <a href="#myModal3" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[1] %></a>
          <!-- Modal -->
          <div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3" aria-hidden="true">
            <% if @x.respuesta ==  @array[1] %>
            <div class="modal-header">                   
              <h3 id="myModalLabel3">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[1] %></p>    
              <p>Bien hecho</p>               
            </div>
               <% @cont = 1 %>     
            <% else %>
            <div class="modal-header">
                
              <h3 id="myModalLabel3">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[1] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
        </div>
            <br >
             <% @cont = 0 %>   
        <% end %>
            <div class="modal-footer">              
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
            <br>         
      
      
      
          <a href="#myModal4" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[3] %></a>
          <!-- Modal -->
          <div id="myModal4" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
            <% if @x.respuesta ==  @array[3] %>
            <div class="modal-header">
                 
              <h3 id="myModalLabel3">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[3] %></p>    
              <p>Bien hecho</p>               
            </div>
              <% @cont = 1 %>     
            <% else %>
            <div class="modal-header">
               
              <h3 id="myModalLabel3">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[3] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
        </div>
            <br >  
             <% @cont = 0 %>   
        <% end %>
            <div class="modal-footer">
             
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
            <br>         
      
        <a href="#myModal5" role="button" class="btn btn-link" data-toggle="modal"><%=  @array[2] %></a>
          <!-- Modal -->
          <div id="myModal5" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
            <% if @x.respuesta ==  @array[2] %>
            <div class="modal-header">                  
              <h3 id="myModalLabel4">Correcto</h3>
            </div>    
            <div class="modal-body"> 
              <p>Usted Preciono <%= @array[2] %></p>    
              <p>Bien hecho</p>               
            </div>
           <% @cont = 1 %>     
            <% else %>
            <div class="modal-header">                  
              <h3 id="myModalLabel4">Incorrecto</h3>
            </div>         
            <div class="modal-body">
               <p>Usted Preciono <%= @array[2] %></p>       
              <p>La respuesta correcta es <%= @x.respuesta %></p>               
            </div>
            <br >   
              <% @cont = 0 %>     
        <% end %>
            <div class="modal-footer">          
              <button class="btn"><%= link_to 'Siguiente', root_path %></button>
            </div>
          </div>
            <br>   
                <% @y = false %>
             <% else %>
                <% @y = true %>
             <% end %>
          <% end %> 
      <% end %>             
     
             <% Contador.all[0].update( id:(Contador.all[0].id), contC:(Contador.all[0].contC +  @cont ), contPg:(Contador.all[0].contPg + 1)) %>
  
              <% if Contador.all[0].contPg > 10  %>
                <% Contador.all[0].update( id:(Contador.all[0].id), contC:0, contPg:1 ) %>
           
             <% end %>
             
             
             
      <br >  
      <a href="#myModal" role="button" class="btn" data-toggle="modal">Pista</a>
      <!-- Modal -->
      <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
       
          <h3 id="myModalLabel">Pista</h3>
        </div>
        <div class="modal-body">
          <p><%= @x.pista %></p>
        </div>
        <div class="modal-footer">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
        </div>
       
        <% end %>
        </div>      
    </div><!-- /.span4 -->
        <div class="span4">         
      
          </div>
        </div><!-- /.span4 -->
      </div><!-- /.row -->
   <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
      </div>
   

 
   <footer>
        <p><%= Contador.all[0].contPg %> de  10 </p>
      </footer>

   </div> <!-- /container -->

app/views/main/show,html.erb
 <p>  You selected <%= @data %></p>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pregunta %><br>
    <%= f.text_field :pregunta %>
    <%= f.label :respuesta %><br>
    <%= f.text_field :respuesta %>
     <%= f.label :pista %><br>
    <%= f.text_field :pista %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editar Preguntas</h1>

<%= render 'form' %>

<%= link_to 'Ver', @question %> |
<%= link_to 'Regresar', questions_path %>

app/views/questions/index.html.erb
<h1>Ver Preguntas</h1>

<table>
  <thead>
    <tr>
      <th>Pregunta</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.pregunta %></td>
        <td><%= link_to 'Ver', question %></td>
        <td><%= link_to 'Editar', edit_question_path(question) %></td>
        <td><%= link_to 'Destruir', question, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Pregunta', new_question_path %>

app/views/questions/new.html.erb
<h1>Nueva Pregunta</h1>

<%= render 'form' %>

<%= link_to 'Regresar', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pregunta:</strong>
  <%= @question.pregunta %>
</p>
<p>
  <strong>Respuesta:</strong>
  <%= @question.respuesta %>
</p>
<p>
  <strong>Pista:</strong>
  <%= @question.pista %>
</p>

<%= link_to 'Editar', edit_question_path(@question) %> |
<%= link_to 'Regresar', questions_path %>